version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - youtube-summarizer-net

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=youtube_summarizer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - youtube-summarizer-net

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - youtube-summarizer-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - youtube-summarizer-net

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - youtube-summarizer-net

  orchestrator:
    build: .
    container_name: orchestrator
    command: python -m src.services.orchestrator_service.app
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - youtube-summarizer-net

  discovery_service:
    build: .
    command: python -m src.services.discovery_service.app
    depends_on:
      - rabbitmq
      - postgres
      - kafka
    networks:
      - youtube-summarizer-net

  download_service:
    build: .
    command: python -m src.services.download_service.app
    depends_on:
      - rabbitmq
      - postgres
      - kafka
    networks:
      - youtube-summarizer-net

  audio_extraction_service:
    build: .
    command: python -m src.services.audio_extraction_service.app
    depends_on:
      - rabbitmq
      - postgres
      - kafka
    networks:
      - youtube-summarizer-net

  transcription_service:
    build: .
    command: python -m src.services.transcription_service.app
    depends_on:
      - rabbitmq
      - postgres
      - mongo
      - kafka
    networks:
      - youtube-summarizer-net

  summarization_service:
    build: .
    command: python -m src.services.summarization_service.app
    ports:
      - "5005:5005"
    depends_on:
      - rabbitmq
      - postgres
      - mongo
      - kafka
    networks:
      - youtube-summarizer-net
  
  logging_service:
    build: .
    command: python -m src.services.logging_service.app
    depends_on:
      - rabbitmq
    networks:
      - youtube-summarizer-net

networks:
  youtube-summarizer-net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
