FROM youtube-channel-summarizer-base-code:latest

WORKDIR /app

COPY src/services/analytics_service/app.py /app/src/services/analytics_service/

CMD ["python", "src/services/analytics_service/app.py"]
