FROM youtube-channel-summarizer-base-code:latest

WORKDIR /app

COPY src/services/orchestrator_service/app.py /app/src/services/orchestrator_service/
COPY apis /app/apis

CMD ["python", "src/services/orchestrator_service/app.py"]
